package com.drishtix.model;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import java.time.LocalDateTime;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Unit tests for {@link PersonEmbedding} POJO — verifies constructor behavior,
 * dimension reporting, nullable targetId support, and timestamp auto-generation.
 */
class PersonEmbeddingTest {

    @Nested
    @DisplayName("Constructor & Defaults")
    class ConstructorTests {

        @Test
        @DisplayName("Full constructor sets all fields correctly")
        void fullConstructor_setsFields() {
            double[] vector = {0.1, 0.2, 0.3};
            PersonEmbedding pe = new PersonEmbedding(42, 1, vector, "/snapshots/img.jpg");

            assertEquals(42, pe.getTargetId());
            assertEquals(1, pe.getCameraId());
            assertArrayEquals(vector, pe.getEmbedding());
            assertEquals("/snapshots/img.jpg", pe.getSnapshotPath());
            assertNotNull(pe.getTimestamp(), "Timestamp should be auto-generated");
        }

        @Test
        @DisplayName("Default constructor creates empty object")
        void defaultConstructor_fieldsNull() {
            PersonEmbedding pe = new PersonEmbedding();

            assertNull(pe.getTargetId());
            assertNull(pe.getCameraId());
            assertNull(pe.getEmbedding());
            assertNull(pe.getSnapshotPath());
            assertEquals(0, pe.getEmbeddingId());
        }

        @Test
        @DisplayName("Null targetId is valid (unknown person)")
        void nullTargetId_isValid() {
            double[] vector = new double[512];
            PersonEmbedding pe = new PersonEmbedding(null, 2, vector, "/snap.jpg");

            assertNull(pe.getTargetId(), "Unknown person should have null targetId");
            assertNotNull(pe.getEmbedding());
        }

        @Test
        @DisplayName("Timestamp is auto-set to approximately now")
        void timestamp_autoGenerated() {
            LocalDateTime before = LocalDateTime.now().minusSeconds(1);
            PersonEmbedding pe = new PersonEmbedding(1, 1, new double[]{0.5}, "/img.jpg");
            LocalDateTime after = LocalDateTime.now().plusSeconds(1);

            assertTrue(pe.getTimestamp().isAfter(before) && pe.getTimestamp().isBefore(after),
                    "Timestamp should be within 1 second of creation");
        }
    }

    @Nested
    @DisplayName("getDimensions()")
    class DimensionsTests {

        @Test
        @DisplayName("512-element array → dimensions = 512")
        void standardEmbedding_returns512() {
            double[] vector = new double[512];
            PersonEmbedding pe = new PersonEmbedding(1, 1, vector, null);
            assertEquals(512, pe.getDimensions());
        }

        @Test
        @DisplayName("3-element array → dimensions = 3")
        void smallEmbedding_returnsCorrectSize() {
            double[] vector = {1.0, 2.0, 3.0};
            PersonEmbedding pe = new PersonEmbedding(1, 1, vector, null);
            assertEquals(3, pe.getDimensions());
        }

        @Test
        @DisplayName("Null embedding → dimensions = 0")
        void nullEmbedding_returnsZero() {
            PersonEmbedding pe = new PersonEmbedding();
            assertEquals(0, pe.getDimensions());
        }

        @Test
        @DisplayName("Empty array → dimensions = 0")
        void emptyEmbedding_returnsZero() {
            PersonEmbedding pe = new PersonEmbedding(1, 1, new double[0], null);
            assertEquals(0, pe.getDimensions());
        }
    }

    @Nested
    @DisplayName("Setters & Getters")
    class SetterGetterTests {

        @Test
        @DisplayName("setEmbeddingId / getEmbeddingId round-trip")
        void embeddingId_roundTrip() {
            PersonEmbedding pe = new PersonEmbedding();
            pe.setEmbeddingId(999L);
            assertEquals(999L, pe.getEmbeddingId());
        }

        @Test
        @DisplayName("setTimestamp / getTimestamp round-trip")
        void timestamp_roundTrip() {
            PersonEmbedding pe = new PersonEmbedding();
            LocalDateTime custom = LocalDateTime.of(2025, 6, 15, 10, 30);
            pe.setTimestamp(custom);
            assertEquals(custom, pe.getTimestamp());
        }

        @Test
        @DisplayName("Transient cameraName / targetName getters/setters")
        void transientFields_roundTrip() {
            PersonEmbedding pe = new PersonEmbedding();
            pe.setCameraName("Front Gate");
            pe.setTargetName("John Doe");
            assertEquals("Front Gate", pe.getCameraName());
            assertEquals("John Doe", pe.getTargetName());
        }
    }

    @Nested
    @DisplayName("toString()")
    class ToStringTests {

        @Test
        @DisplayName("toString includes key fields")
        void toString_includesKeyFields() {
            double[] v = new double[512];
            PersonEmbedding pe = new PersonEmbedding(5, 2, v, "/img.jpg");
            pe.setEmbeddingId(100);

            String str = pe.toString();
            assertTrue(str.contains("id=100"));
            assertTrue(str.contains("targetId=5"));
            assertTrue(str.contains("cameraId=2"));
            assertTrue(str.contains("dims=512"));
        }
    }
}
