package com.drishtix.model;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Unit tests for {@link ReIDMatch} — verifies the immutable value object
 * that represents a cross-camera person re-identification event.
 */
class ReIDMatchTest {

    private PersonEmbedding createEmbedding(long id, Integer cameraId, Integer targetId) {
        PersonEmbedding pe = new PersonEmbedding(targetId, cameraId, new double[512], "/snap.jpg");
        pe.setEmbeddingId(id);
        return pe;
    }

    @Nested
    @DisplayName("Constructor & Getters")
    class ConstructorTests {

        @Test
        @DisplayName("Constructor stores source, matched, and similarity")
        void constructor_storesAllFields() {
            PersonEmbedding source = createEmbedding(1, 1, 10);
            PersonEmbedding matched = createEmbedding(2, 2, 10);

            ReIDMatch match = new ReIDMatch(source, matched, 0.923);

            assertSame(source, match.getSourceEmbedding());
            assertSame(matched, match.getMatchedEmbedding());
            assertEquals(0.923, match.getSimilarity(), 1e-9);
            assertNotNull(match.getMatchTime());
        }

        @Test
        @DisplayName("Match time is auto-generated at construction")
        void matchTime_autoGenerated() {
            PersonEmbedding s = createEmbedding(1, 1, null);
            PersonEmbedding m = createEmbedding(2, 2, null);

            ReIDMatch match = new ReIDMatch(s, m, 0.9);

            assertNotNull(match.getMatchTime());
        }
    }

    @Nested
    @DisplayName("getSimilarityPercentage()")
    class SimilarityPercentageTests {

        @Test
        @DisplayName("0.923 → '92.3%'")
        void percentage_formattedCorrectly() {
            ReIDMatch match = new ReIDMatch(
                    createEmbedding(1, 1, null),
                    createEmbedding(2, 2, null),
                    0.923
            );
            assertEquals("92.3%", match.getSimilarityPercentage());
        }

        @Test
        @DisplayName("1.0 → '100.0%'")
        void perfectMatch_hundred() {
            ReIDMatch match = new ReIDMatch(
                    createEmbedding(1, 1, null),
                    createEmbedding(2, 2, null),
                    1.0
            );
            assertEquals("100.0%", match.getSimilarityPercentage());
        }

        @Test
        @DisplayName("0.85 → '85.0%'")
        void thresholdMatch_eightyfive() {
            ReIDMatch match = new ReIDMatch(
                    createEmbedding(1, 1, null),
                    createEmbedding(2, 2, null),
                    0.85
            );
            assertEquals("85.0%", match.getSimilarityPercentage());
        }

        @Test
        @DisplayName("0.0 → '0.0%'")
        void zeroSimilarity_zero() {
            ReIDMatch match = new ReIDMatch(
                    createEmbedding(1, 1, null),
                    createEmbedding(2, 2, null),
                    0.0
            );
            assertEquals("0.0%", match.getSimilarityPercentage());
        }
    }

    @Nested
    @DisplayName("Camera ID Accessors")
    class CameraIdTests {

        @Test
        @DisplayName("getSourceCameraId returns source embedding's camera")
        void sourceCameraId_fromSourceEmbedding() {
            ReIDMatch match = new ReIDMatch(
                    createEmbedding(1, 3, null),
                    createEmbedding(2, 7, null),
                    0.9
            );
            assertEquals(3, match.getSourceCameraId());
        }

        @Test
        @DisplayName("getMatchedCameraId returns matched embedding's camera")
        void matchedCameraId_fromMatchedEmbedding() {
            ReIDMatch match = new ReIDMatch(
                    createEmbedding(1, 3, null),
                    createEmbedding(2, 7, null),
                    0.9
            );
            assertEquals(7, match.getMatchedCameraId());
        }

        @Test
        @DisplayName("Null source embedding → null source camera ID")
        void nullSourceEmbedding_returnsNullCameraId() {
            ReIDMatch match = new ReIDMatch(null, createEmbedding(2, 5, null), 0.9);
            assertNull(match.getSourceCameraId());
        }

        @Test
        @DisplayName("Null matched embedding → null matched camera ID")
        void nullMatchedEmbedding_returnsNullCameraId() {
            ReIDMatch match = new ReIDMatch(createEmbedding(1, 3, null), null, 0.9);
            assertNull(match.getMatchedCameraId());
        }
    }

    @Nested
    @DisplayName("toString()")
    class ToStringTests {

        @Test
        @DisplayName("toString contains similarity formatted to 3 decimals")
        void toString_containsSimilarity() {
            ReIDMatch match = new ReIDMatch(
                    createEmbedding(10, 1, null),
                    createEmbedding(20, 2, null),
                    0.9234
            );
            String str = match.toString();
            assertTrue(str.contains("source=10"), "Should contain source ID");
            assertTrue(str.contains("matched=20"), "Should contain matched ID");
            assertTrue(str.contains("0.923"), "Should contain similarity to 3 decimals");
        }

        @Test
        @DisplayName("Null embeddings produce 'null' in toString")
        void toString_handlesNullEmbeddings() {
            ReIDMatch match = new ReIDMatch(null, null, 0.5);
            String str = match.toString();
            assertTrue(str.contains("source=null"));
            assertTrue(str.contains("matched=null"));
        }
    }
}
